### ISSUE TITLE
Cross-Origin Request Blocked issue on wiktionary-scraper

### ISSUE THREAD

**Issue by CodePapa360** [vxern/wiktionary-scraper#1]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at (The link)#English. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

**Comment by vxern** [comment]
Hi, could you provide some context about how you used the package and the stack trace of your issue? It will help in diagnosing it.

**Comment by CodePapa360** [comment]
I tried in a React project with fetch. But it gave me this error.

**Comment by vxern** [comment]
Right. The package has not been tested to run in the browser so it makes sense that this CORS issue is present, I'll look into making sure it works in the browser when I get some free time.

**Comment by vxern** [comment]
For the time being, if you need to get the library working, as a temporary measure, you could fork the library and add the headers yourself until a new release is ready.

**Comment by vxern** [comment]
I had a quick look.

Wiktionary does not return CORS headers for paths not accessing its API endpoints. `wiktionary-scraper` does not work with the Wiktionary API, but rather, it requests paths under `/wiki/` and scrapes their content. (for example `https://en.wiktionary.org/wiki/my-word-here`)

The only way I could make this work would be to pass requests through a proxy that would include `Access-Control-Allow-Origin`, but this is a complete no-go since it is a public package and I cannot rely on proxies, especially public ones.

You can still make `wiktionary-scraper` work for your app by simply running it server-side and exposing an endpoint to use it.

**Comment by 2colours** [comment]
What this package could still allow to mitigate the situation somewhat, is user-specified endpoint URL's, rather than having it hardcoded inside the package.

That way, the website could define a same-origin endpoint and then simply add a redirect rule to that endpoint in the used web server. I feel this is simpler than making the scraper into a service by yourself.

**Comment by vxern** [comment]
That's a fair point, there should definitely be a way to override the endpoint. It would also be a trivial change, so I'll implement that, at least.
